version: '3'
services:
  postgres:
    container_name: postgres
    image: "postgres"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
    networks:
    - compose-bridge     
    ports:
      - "5432:5432"
    volumes:
     - ./postgres-data:/var/lib/postgresql/data  

  api:
    container_name: api
    image: nat/meuapp  
    networks:
    - compose-bridge 
    ports:
    - "8080:8080" 
    depends_on:
      - postgres


  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "nat@nat.com"
      PGADMIN_DEFAULT_PASSWORD: "123456"
    ports:
      - "12345:80"
    depends_on:
      - postgres


networks:
    compose-bridge:
      driver: bridge
